<?php

/**
 * @file
 * Supports Islandora submodule islandora_mirador.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_theme().
 */
function islandora_mirador_theme() {
  return [
    'mirador' => [
      'variables' => [
        'iiif_manifest_url' => NULL,
        'mirador_view_id' => NULL,
      ],
      'template' => 'mirador',
    ],
  ];
}

/**
 * Implements template_preprocess_*().
 */
function template_preprocess_mirador(&$variables) {
  $variables['mirador_view_id'] = Html::getUniqueId($variables['mirador_view_id']);
  $variables['#attached']['drupalSettings']['mirador_view_id'] = $variables['mirador_view_id'];

  // For dsu-utsc.
  if (!empty(\Drupal::hasService('jwt.authentication.jwt'))) {
    $variables['#attached']['drupalSettings']['token'] = \Drupal::service('jwt.authentication.jwt')->generateToken();
  }

}
